-- HABILITAR EXTENSÃO PARA GERAÇÃO DE UUID
CREATE EXTENSION IF NOT EXISTS "PGCRYPTO";

-- ==========================================
-- CRIAÇÃO DAS TABELAS
-- ==========================================

-- 1. TABELA: CATEGORIAS
CREATE TABLE IF NOT EXISTS CATEGORIAS (
    ID UUID PRIMARY KEY DEFAULT GEN_RANDOM_UUID(),
    NOME VARCHAR(100) NOT NULL UNIQUE
);

-- 2. TABELA: CLIENTES
CREATE TABLE IF NOT EXISTS CLIENTES (
    ID UUID PRIMARY KEY DEFAULT GEN_RANDOM_UUID(),
    NOME VARCHAR(255) NOT NULL,
    CPF VARCHAR(14) NOT NULL UNIQUE,
    TELEFONE VARCHAR(20) NOT NULL UNIQUE,
    CRIADO_EM TIMESTAMP NOT NULL DEFAULT NOW()
);

-- 3. TABELA: PECAS
CREATE TABLE IF NOT EXISTS PECAS (
    ID UUID PRIMARY KEY DEFAULT GEN_RANDOM_UUID(),
    CODIGO VARCHAR(50) NOT NULL UNIQUE,
    NOME VARCHAR(255) NOT NULL,
    CATEGORIA_ID UUID NOT NULL REFERENCES CATEGORIAS(ID),
    PRECO NUMERIC(10,2) NOT NULL CHECK (PRECO > 0),
    QTD_ESTOQUE INTEGER NOT NULL CHECK (QTD_ESTOQUE >= 0),
    SITUACAO VARCHAR(10) NOT NULL DEFAULT 'ATIVA' CHECK (SITUACAO IN ('ATIVA', 'INATIVA')),
    CRIADO_EM TIMESTAMP NOT NULL DEFAULT NOW()
);

-- 4. TABELA: PEDIDOS
CREATE TABLE IF NOT EXISTS PEDIDOS (
    ID UUID PRIMARY KEY DEFAULT GEN_RANDOM_UUID(),
    NUMERO VARCHAR(30) NOT NULL UNIQUE,
    CLIENTE_ID UUID NOT NULL REFERENCES CLIENTES(ID),
    STATUS VARCHAR(15) NOT NULL DEFAULT 'PENDENTE' CHECK (STATUS IN ('PENDENTE', 'CONFIRMADO', 'CANCELADO')),
    VALOR_TOTAL NUMERIC(10,2) NOT NULL DEFAULT 0.00 CHECK (VALOR_TOTAL >= 0),
    CRIADO_EM TIMESTAMP NOT NULL DEFAULT NOW(),
    ATUALIZADO_EM TIMESTAMP NOT NULL DEFAULT NOW()
);

-- 5. TABELA: ITENS_PEDIDO
CREATE TABLE IF NOT EXISTS ITENS_PEDIDO (
    ID UUID PRIMARY KEY DEFAULT GEN_RANDOM_UUID(),
    PEDIDO_ID UUID NOT NULL REFERENCES PEDIDOS(ID) ON DELETE CASCADE,
    PECA_ID UUID NOT NULL REFERENCES PECAS(ID),
    QUANTIDADE INTEGER NOT NULL CHECK (QUANTIDADE > 0),
    PRECO_UNITARIO NUMERIC(10,2) NOT NULL CHECK (PRECO_UNITARIO > 0),
    SUBTOTAL NUMERIC(10,2) NOT NULL CHECK (SUBTOTAL >= 0)
);